name: Docker Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build
      run: |
        docker build -t test-container .
        docker run --name test-container -d --privileged test-container
        docker exec --tty test-container env TERM=xterm ps aux
        
 
